[project]
name = "basketball_reference_web_scraper"
version = "4.15.4"
description = "A Basketball Reference client that generates data by scraping the website"
authors = [{ name = "Jae Bradley", email = "jae.b.bradley@gmail.com" }]
requires-python = ">=3.7,<4"
readme = "README.md"
license = "MIT"
maintainers = [{ name = "Jae Bradley", email = "jae.b.bradley@gmail.com" }]
keywords = [
    "NBA",
    "Basketball",
    "Basketball",
    "Reference",
    "basketball-reference.com",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "lxml>=5.1.0,<6",
    "pytz>=2024.1,<2025",
    "requests>=2.31.0,<3",
]

[project.urls]
Homepage = "https://jaebradley.github.io/basketball_reference_web_scraper"
Repository = "https://github.com/jaebradley/basketball_reference_web_scraper"
issues = "https://github.com/jaebradley/basketball_reference_web_scraper/issues"
pull_requests = "https://github.com/jaebradley/basketball_reference_web_scraper/pull_requests"

[dependency-groups]
dev = [
    "codecov>=2.1.13,<3",
    "mkdocs>=1.5.3,<2",
    "mkdocs-material<= 9.2.8",
    "pymdown-extensions<= 10.2.1",
    "coverage<= 7.2.7",
    "pytest<= 7.4.4",
    "requests-mock>=1.12.1,<2",
]

[tool.uv]

[tool.uv.build-backend]
module-root = ""
source-exclude = [
    "tests",
    "docs",
]
wheel-exclude = [
    "tests",
    "docs",
]

[build-system]
requires = ["uv_build>=0.11.26,<0.12.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = "basketball_reference_web_scraper"
testpaths = "tests"
addopts = [
    "--import-mode=importlib",
]
