[project]
name = "basketball_reference_web_scraper"
version = "4.19.0"
description = "A Basketball Reference client that generates data by scraping the website"
authors = [{ name = "Jae Bradley", email = "jae.b.bradley@gmail.com" }]
requires-python = ">=3.10,<4"
readme = "README.md"
license = "MIT"
maintainers = [{ name = "Jae Bradley", email = "jae.b.bradley@gmail.com" }]
keywords = [
    "NBA",
    "Basketball",
    "Basketball",
    "Reference",
    "basketball-reference.com",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "lxml>=6.1.1,<7",
    "requests>=2.34.2,<3",
]

[project.urls]
Homepage = "https://jaebradley.github.io/basketball_reference_web_scraper"
Repository = "https://github.com/jaebradley/basketball_reference_web_scraper"
issues = "https://github.com/jaebradley/basketball_reference_web_scraper/issues"
pull_requests = "https://github.com/jaebradley/basketball_reference_web_scraper/pull_requests"

[dependency-groups]
dev = [
    "codecov==2.1.13",
    "mkdocs==1.6.1",
    "mkdocs-material==9.7.6",
    "pymdown-extensions==11.0",
    "coverage==7.14.3",
    "pytest==9.1.1",
    "requests-mock==1.12.1",
]

[tool.uv]

[tool.uv.build-backend]
module-root = ""
source-exclude = [
    "tests",
    "docs",
]
wheel-exclude = [
    "tests",
    "docs",
]

[build-system]
requires = ["uv_build>=0.11.26,<0.12.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = "basketball_reference_web_scraper"
testpaths = "tests"
addopts = [
    "--import-mode=importlib",
]
