from enum import Enum


class Location(Enum):
    HOME = "HOME"
    AWAY = "AWAY"


class Outcome(Enum):
    WIN = "WIN"
    LOSS = "LOSS"


class Team(Enum):
    # Look at https://www.basketball-reference.com/teams/ for all teams
    ATLANTA_HAWKS = "ATLANTA HAWKS"
    BOSTON_CELTICS = "BOSTON CELTICS"
    BROOKLYN_NETS = "BROOKLYN NETS"
    CHARLOTTE_HORNETS = "CHARLOTTE HORNETS"
    CHICAGO_BULLS = "CHICAGO BULLS"
    CLEVELAND_CAVALIERS = "CLEVELAND CAVALIERS"
    DALLAS_MAVERICKS = "DALLAS MAVERICKS"
    DENVER_NUGGETS = "DENVER NUGGETS"
    DETROIT_PISTONS = "DETROIT PISTONS"
    GOLDEN_STATE_WARRIORS = "GOLDEN STATE WARRIORS"
    HOUSTON_ROCKETS = "HOUSTON ROCKETS"
    INDIANA_PACERS = "INDIANA PACERS"
    LOS_ANGELES_CLIPPERS = "LOS ANGELES CLIPPERS"
    LOS_ANGELES_LAKERS = "LOS ANGELES LAKERS"
    MEMPHIS_GRIZZLIES = "MEMPHIS GRIZZLIES"
    MIAMI_HEAT = "MIAMI HEAT"
    MILWAUKEE_BUCKS = "MILWAUKEE BUCKS"
    MINNESOTA_TIMBERWOLVES = "MINNESOTA TIMBERWOLVES"
    NEW_ORLEANS_PELICANS = "NEW ORLEANS PELICANS"
    NEW_YORK_KNICKS = "NEW YORK KNICKS"
    OKLAHOMA_CITY_THUNDER = "OKLAHOMA CITY THUNDER"
    ORLANDO_MAGIC = "ORLANDO MAGIC"
    PHILADELPHIA_76ERS = "PHILADELPHIA 76ERS"
    PHOENIX_SUNS = "PHOENIX SUNS"
    PORTLAND_TRAIL_BLAZERS = "PORTLAND TRAIL BLAZERS"
    SACRAMENTO_KINGS = "SACRAMENTO KINGS"
    SAN_ANTONIO_SPURS = "SAN ANTONIO SPURS"
    TORONTO_RAPTORS = "TORONTO RAPTORS"
    UTAH_JAZZ = "UTAH JAZZ"
    WASHINGTON_WIZARDS = "WASHINGTON WIZARDS"

    # DEPRECATED TEAMS
    ANDERSON_PACKERS = "ANDERSON PACKERS"
    BALTIMORE_BULLETS = "BALTIMORE BULLETS"
    BUFFALO_BRAVES = "BUFFALO BRAVES"
    CAPITAL_BULLETS = "CAPITAL BULLETS"
    CHARLOTTE_BOBCATS = "CHARLOTTE BOBCATS"
    CHICAGO_PACKERS = "CHICAGO PACKERS"
    CHICAGO_STAGS = "CHICAGO STAGS"
    CHICAGO_ZEPHYRS = "CHICAGO ZEPHYRS"
    CINCINNATI_ROYALS = "CINCINNATI ROYALS"
    FORT_WAYNE_PISTONS = "FORT WAYNE PISTONS"
    INDIANAPOLIS_OLYMPIANS = "INDIANAPOLIS OLYMPIANS"
    KANSAS_CITY_KINGS = "KANSAS CITY KINGS"
    KANSAS_CITY_OMAHA_KINGS = "KANSAS CITY-OMAHA KINGS"
    MILWAUKEE_HAWKS = "MILWAUKEE HAWKS"
    MINNEAPOLIS_LAKERS = "MINNEAPOLIS LAKERS"
    NEW_JERSEY_NETS = "NEW JERSEY NETS"
    NEW_ORLEANS_HORNETS = "NEW ORLEANS HORNETS"
    NEW_ORLEANS_OKLAHOMA_CITY_HORNETS = "NEW ORLEANS/OKLAHOMA CITY HORNETS"
    PHILADELPHIA_WARRIORS = "PHILADELPHIA WARRIORS"
    ROCHESTER_ROYALS = "ROCHESTER ROYALS"
    SAN_DIEGO_CLIPPERS = "SAN DIEGO CLIPPERS"
    SAN_DIEGO_ROCKETS = "SAN DIEGO ROCKETS"
    SAN_FRANCISCO_WARRIORS = "SAN FRANCISCO WARRIORS"
    SEATTLE_SUPERSONICS = "SEATTLE SUPERSONICS"
    SHEBOYGAN_RED_SKINS = "SHEBOYGAN RED SKINS"
    ST_LOUIS_BOMBERS = "ST. LOUIS BOMBERS"
    ST_LOUIS_HAWKS = "ST. LOUIS HAWKS"
    SYRACUSE_NATIONALS = "SYRACUSE NATIONALS"
    TRI_CITIES_BLACKHAWKS = "TRI-CITIES BLACKHAWKS"
    VANCOUVER_GRIZZLIES = "VANCOUVER GRIZZLIES"
    WASHINGTON_CAPITOLS = "WASHINGTON CAPITOLS"
    WATERLOO_HAWKS = "WATERLOO HAWKS"


class OutputType(Enum):
    JSON = "JSON"
    CSV = "CSV"


class OutputWriteOption(Enum):
    WRITE = "w"
    CREATE_AND_WRITE = "w+"
    APPEND = "a"
    APPEND_AND_WRITE = "a+"


class Position(Enum):
    POINT_GUARD = "POINT GUARD"
    SHOOTING_GUARD = "SHOOTING GUARD"
    SMALL_FORWARD = "SMALL FORWARD"
    POWER_FORWARD = "POWER FORWARD"
    CENTER = "CENTER"
    FORWARD = "FORWARD"
    GUARD = "GUARD"


class PeriodType(Enum):
    QUARTER = "QUARTER"
    OVERTIME = "OVERTIME"


TEAM_ABBREVIATIONS_TO_TEAM = {
    'ATL': Team.ATLANTA_HAWKS,
    'BOS': Team.BOSTON_CELTICS,
    'BRK': Team.BROOKLYN_NETS,
    'CHI': Team.CHICAGO_BULLS,
    'CHO': Team.CHARLOTTE_HORNETS,
    'CLE': Team.CLEVELAND_CAVALIERS,
    'DAL': Team.DALLAS_MAVERICKS,
    'DEN': Team.DENVER_NUGGETS,
    'DET': Team.DETROIT_PISTONS,
    'GSW': Team.GOLDEN_STATE_WARRIORS,
    'HOU': Team.HOUSTON_ROCKETS,
    'IND': Team.INDIANA_PACERS,
    'LAC': Team.LOS_ANGELES_CLIPPERS,
    'LAL': Team.LOS_ANGELES_LAKERS,
    'MEM': Team.MEMPHIS_GRIZZLIES,
    'MIA': Team.MIAMI_HEAT,
    'MIL': Team.MILWAUKEE_BUCKS,
    'MIN': Team.MINNESOTA_TIMBERWOLVES,
    'NOP': Team.NEW_ORLEANS_PELICANS,
    'NYK': Team.NEW_YORK_KNICKS,
    'OKC': Team.OKLAHOMA_CITY_THUNDER,
    'ORL': Team.ORLANDO_MAGIC,
    'PHI': Team.PHILADELPHIA_76ERS,
    'PHO': Team.PHOENIX_SUNS,
    'POR': Team.PORTLAND_TRAIL_BLAZERS,
    'SAC': Team.SACRAMENTO_KINGS,
    'SAS': Team.SAN_ANTONIO_SPURS,
    'TOR': Team.TORONTO_RAPTORS,
    'UTA': Team.UTAH_JAZZ,
    'WAS': Team.WASHINGTON_WIZARDS,

    # DEPRECATED TEAMS
    # https://www.basketball-reference.com/teams/AND/1950.html
    'AND': Team.ANDERSON_PACKERS,
    # https://www.basketball-reference.com/teams/BLB/1950.html
    'BLB': Team.BALTIMORE_BULLETS,
    # https://www.basketball-reference.com/teams/BUF/1971.html
    'BUF': Team.BUFFALO_BRAVES,
    # https://www.basketball-reference.com/teams/CAP/1974.html
    'CAP': Team.CAPITAL_BULLETS,
    'CHA': Team.CHARLOTTE_BOBCATS,
    'CHH': Team.CHARLOTTE_HORNETS,
    # https://www.basketball-reference.com/teams/CHP/1962.html
    'CHP': Team.CHICAGO_PACKERS,
    # https://www.basketball-reference.com/teams/CHS/1950.html
    'CHS': Team.CHICAGO_STAGS,
    # https://www.basketball-reference.com/teams/CHZ/1963.html
    'CHZ': Team.CHICAGO_ZEPHYRS,
    # https://www.basketball-reference.com/teams/CIN/1971.html
    'CIN': Team.CINCINNATI_ROYALS,
    # https://www.basketball-reference.com/teams/FTW/1950.html
    'FTW': Team.FORT_WAYNE_PISTONS,
    # https://www.basketball-reference.com/teams/INO/1950.html
    'INO': Team.INDIANAPOLIS_OLYMPIANS,
    # https://www.basketball-reference.com/teams/KCK/1976.html
    'KCK': Team.KANSAS_CITY_KINGS,
    # https://www.basketball-reference.com/teams/KCO/1973.html
    'KCO': Team.KANSAS_CITY_OMAHA_KINGS,
    # https://www.basketball-reference.com/teams/MLH/1952.html
    'MLH': Team.MILWAUKEE_HAWKS,
    # https://www.basketball-reference.com/teams/MNL/1950.html
    'MNL': Team.MINNEAPOLIS_LAKERS,
    'NJN': Team.NEW_JERSEY_NETS,
    'NOH': Team.NEW_ORLEANS_HORNETS,
    'NOK': Team.NEW_ORLEANS_OKLAHOMA_CITY_HORNETS,
    # https://www.basketball-reference.com/teams/PHW/1950.html
    'PHW': Team.PHILADELPHIA_WARRIORS,
    # https://www.basketball-reference.com/teams/ROC/1950.html
    'ROC': Team.ROCHESTER_ROYALS,
    # https://www.basketball-reference.com/teams/SDC/1979.html
    'SDC': Team.SAN_DIEGO_CLIPPERS,
    # https://www.basketball-reference.com/teams/SDR/1971.html
    'SDR': Team.SAN_DIEGO_ROCKETS,
    # https://www.basketball-reference.com/teams/SFW/1971.html
    'SFW': Team.SAN_FRANCISCO_WARRIORS,
    'SEA': Team.SEATTLE_SUPERSONICS,
    # https://www.basketball-reference.com/teams/SHE/1950.html
    'SHE': Team.SHEBOYGAN_RED_SKINS,
    # https://www.basketball-reference.com/teams/STB/1950.html
    'STB': Team.ST_LOUIS_BOMBERS,
    # https://www.basketball-reference.com/teams/STL/1962.html
    'STL': Team.ST_LOUIS_HAWKS,
    # https://www.basketball-reference.com/teams/SYR/1950.html
    'SYR': Team.SYRACUSE_NATIONALS,
    # https://www.basketball-reference.com/teams/TRI/1950.html
    'TRI': Team.TRI_CITIES_BLACKHAWKS,
    'VAN': Team.VANCOUVER_GRIZZLIES,
    # https://www.basketball-reference.com/teams/WSC/1950.html
    'WSC': Team.WASHINGTON_CAPITOLS,
    # https://www.basketball-reference.com/teams/WAT/1950.html
    'WAT': Team.WATERLOO_HAWKS,
}

TEAM_TO_TEAM_ABBREVIATION = {v: k for k, v in TEAM_ABBREVIATIONS_TO_TEAM.items()}
TEAM_TO_TEAM_ABBREVIATION[Team.CHARLOTTE_HORNETS] = "CHO"

TEAM_NAME_TO_TEAM = {
    "ATLANTA HAWKS": Team.ATLANTA_HAWKS,
    "BOSTON CELTICS": Team.BOSTON_CELTICS,
    "BROOKLYN NETS": Team.BROOKLYN_NETS,
    "CHARLOTTE HORNETS": Team.CHARLOTTE_HORNETS,
    "CHICAGO BULLS": Team.CHICAGO_BULLS,
    "CLEVELAND CAVALIERS": Team.CLEVELAND_CAVALIERS,
    "DALLAS MAVERICKS": Team.DALLAS_MAVERICKS,
    "DENVER NUGGETS": Team.DENVER_NUGGETS,
    "DETROIT PISTONS": Team.DETROIT_PISTONS,
    "GOLDEN STATE WARRIORS": Team.GOLDEN_STATE_WARRIORS,
    "HOUSTON ROCKETS": Team.HOUSTON_ROCKETS,
    "INDIANA PACERS": Team.INDIANA_PACERS,
    "LOS ANGELES CLIPPERS": Team.LOS_ANGELES_CLIPPERS,
    "LOS ANGELES LAKERS": Team.LOS_ANGELES_LAKERS,
    "MEMPHIS GRIZZLIES": Team.MEMPHIS_GRIZZLIES,
    "MIAMI HEAT": Team.MIAMI_HEAT,
    "MILWAUKEE BUCKS": Team.MILWAUKEE_BUCKS,
    "MINNESOTA TIMBERWOLVES": Team.MINNESOTA_TIMBERWOLVES,
    "NEW ORLEANS PELICANS": Team.NEW_ORLEANS_PELICANS,
    "NEW YORK KNICKS": Team.NEW_YORK_KNICKS,
    "OKLAHOMA CITY THUNDER": Team.OKLAHOMA_CITY_THUNDER,
    "ORLANDO MAGIC": Team.ORLANDO_MAGIC,
    "PHILADELPHIA 76ERS": Team.PHILADELPHIA_76ERS,
    "PHOENIX SUNS": Team.PHOENIX_SUNS,
    "PORTLAND TRAIL BLAZERS": Team.PORTLAND_TRAIL_BLAZERS,
    "SACRAMENTO KINGS": Team.SACRAMENTO_KINGS,
    "SAN ANTONIO SPURS": Team.SAN_ANTONIO_SPURS,
    "TORONTO RAPTORS": Team.TORONTO_RAPTORS,
    "UTAH JAZZ": Team.UTAH_JAZZ,
    "WASHINGTON WIZARDS": Team.WASHINGTON_WIZARDS,

    # DEPRECATED TEAMS
    "ANDERSON PACKERS": Team.ANDERSON_PACKERS,
    "BALTIMORE BULLETS": Team.BALTIMORE_BULLETS,
    "BUFFALO BRAVES": Team.BUFFALO_BRAVES,
    "CAPITAL BULLETS": Team.CAPITAL_BULLETS,
    "CHARLOTTE BOBCATS": Team.CHARLOTTE_BOBCATS,
    "CHICAGO PACKERS": Team.CHICAGO_PACKERS,
    "CHICAGO STAGS": Team.CHICAGO_STAGS,
    "CHICAGO ZEPHYRS": Team.CHICAGO_ZEPHYRS,
    "CINCINNATI ROYALS": Team.CINCINNATI_ROYALS,
    "FORT WAYNE PISTONS": Team.FORT_WAYNE_PISTONS,
    "INDIANAPOLIS OLYMPIANS": Team.INDIANAPOLIS_OLYMPIANS,
    "KANSAS CITY KINGS": Team.KANSAS_CITY_KINGS,
    "KANSAS CITY-OMAHA KINGS": Team.KANSAS_CITY_OMAHA_KINGS,
    "MILWAUKEE HAWKS": Team.MILWAUKEE_HAWKS,
    "MINNEAPOLIS LAKERS": Team.MINNEAPOLIS_LAKERS,
    "NEW JERSEY NETS": Team.NEW_JERSEY_NETS,
    "NEW ORLEANS HORNETS": Team.NEW_ORLEANS_HORNETS,
    "NEW ORLEANS/OKLAHOMA CITY HORNETS": Team.NEW_ORLEANS_OKLAHOMA_CITY_HORNETS,
    "PHILADELPHIA WARRIORS": Team.PHILADELPHIA_WARRIORS,
    "ROCHESTER ROYALS": Team.ROCHESTER_ROYALS,
    "SAN DIEGO CLIPPERS": Team.SAN_DIEGO_CLIPPERS,
    "SAN DIEGO ROCKETS": Team.SAN_DIEGO_ROCKETS,
    "SAN FRANCISCO WARRIORS": Team.SAN_FRANCISCO_WARRIORS,
    "SEATTLE SUPERSONICS": Team.SEATTLE_SUPERSONICS,
    "SHEBOYGAN RED SKINS": Team.SHEBOYGAN_RED_SKINS,
    "ST. LOUIS BOMBERS": Team.ST_LOUIS_BOMBERS,
    "ST. LOUIS HAWKS": Team.ST_LOUIS_HAWKS,
    "SYRACUSE NATIONALS": Team.SYRACUSE_NATIONALS,
    "TRI-CITIES BLACKHAWKS": Team.TRI_CITIES_BLACKHAWKS,
    "VANCOUVER GRIZZLIES": Team.VANCOUVER_GRIZZLIES,
    "WASHINGTON CAPITOLS": Team.WASHINGTON_CAPITOLS,
    "WATERLOO HAWKS": Team.WATERLOO_HAWKS,
}

POSITION_ABBREVIATIONS_TO_POSITION = {
    "PG": Position.POINT_GUARD,
    "SG": Position.SHOOTING_GUARD,
    "SF": Position.SMALL_FORWARD,
    "PF": Position.POWER_FORWARD,
    "C": Position.CENTER,
    "F": Position.FORWARD,
    "G": Position.GUARD,
}
